# Generated by Django 3.2 on 2021-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('EN', 'Enquiry'), ('CM', 'Complain')], default='EN', max_length=2)),
            ],
        ),
    ]
