# Generated by Django 3.2 on 2021-05-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_billingaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_addres',
            new_name='street_address',
        ),
    ]
