# Generated by Django 3.2 on 2021-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_street_addres_billingaddress_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
