# Generated by Django 3.2 on 2021-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210505_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='county',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
