# Generated by Django 3.2 on 2021-04-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
