# Generated by Django 3.2 on 2021-04-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
