# Generated by Django 3.2 on 2021-04-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description asgstdhdsga hsgragreg rgsdrgarg'),
            preserve_default=False,
        ),
    ]
