# Generated by Django 3.2 on 2021-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210427_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Helmets'), ('B', 'Boots'), ('O', 'Outwear'), ('A', 'Accesories')], max_length=2),
        ),
    ]
