# Generated by Django 3.2 on 2021-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='product_image'),
        ),
    ]
