# Generated by Django 3.2 on 2021-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Helmets'), ('B', 'Boots'), ('O', 'Outwear'), ('A', 'Accessories')], max_length=2),
        ),
    ]
