# Generated by Django 3.2 on 2021-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
