# Generated by Django 3.2 on 2021-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_active_carousel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='link_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
