# Generated by Django 3.2 on 2021-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210503_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_information',
            field=models.TextField(null=True),
        ),
    ]
