# Generated by Django 3.2 on 2021-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_item_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category2',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
